language: java
sudo: required
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "vatbub-github"
cache:
  directories:
  - "$HOME/.m2"
install:
- wget https://s3.eu-central-1.amazonaws.com/vatbubjdk/jdk-8u191-linux-x64.tar.gz -nv
- tar -xf jdk-8u191-linux-x64.tar.gz
- export JAVA_HOME=/home/travis/build/vatbub/safeAPIKeyStore/jdk1.8.0_191/
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar --settings travisMavenSettings.xml
after_success:
  - source ./travisAfterSuccess.sh
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_8836c78d5219_key -iv $encrypted_8836c78d5219_iv
  -in github_deploy_key.enc -out github_deploy_key -d
